export const MENU_CARDS = [
    {
        label: 'Crear informe',
        icon: 'file-plus-outline',
        color: '#2456ee',
        bg: '#EFF6FF',
        route: 'CrearInforme',
        permiso: 'crear_informes',
        roles: ['admin', 'empleado'],
    },
    {
        label: 'Consultar informes',
        icon: 'file-document-outline',
        color: '#EF5350',
        bg: '#FFF5F5',
        route: 'Carpetas',
        permiso: 'ver_informes',
        roles: ['admin'],
    },
    {
        label: 'Gestionar informe',
        icon: 'paperclip',
        color: '#EF5350',
        bg: '#FFF5F5',
        route: 'Carpetas',
        permiso: 'ver_informes',
        roles: ['empleado'],
    },
    {
        label: 'Historial',
        icon: 'folder-open-outline',
        color: '#F59E0B',
        bg: '#FFFBEB',
        route: 'Carpetas',
        permiso: 'ver_informes',
        roles: ['empleado'],
    },
    {
        label: 'Consultar usuarios',
        icon: 'account-group-outline',
        color: '#4CAF50',
        bg: '#E8F5E9',
        route: 'Usuarios',
        permiso: 'ver_usuarios',
        roles: ['admin'],
    },
    {
        label: 'Crear usuarios',
        icon: 'account-plus-outline',
        color: '#2456ee',
        bg: '#EFF6FF',
        route: 'CrearUsuario',
        permiso: 'crear_usuarios',
        roles: ['admin'],
    },
    {
        label: 'Novedades',
        icon: 'newspaper-variant-outline',
        color: '#F59E0B',
        bg: '#FFFBEB',
        route: 'Novedades',
        permiso: 'ver_novedades',
        roles: ['admin'],
    },
    {
        label: 'Pendientes',
        icon: 'clipboard-list-outline',
        color: '#FF9800',
        bg: '#FFF8F0',
        route: 'Novedades',
        permiso: 'ver_novedades',
        roles: ['empleado'],
    },
    {
        label: 'Gráficos',
        icon: 'chart-bar',
        color: '#FF9800',
        bg: '#FFF3E0',
        route: 'Graficos',
        permiso: 'ver_graficos',
        roles: ['admin'],
    },
];

export const BOTTOM_NAV_CONFIG = {
    admin: [
        { icon: 'account-outline', route: 'Home' },
        { icon: 'cog-outline',     route: 'Configuracion' },
        { icon: 'bell-outline',    route: 'Novedades' },
        { icon: 'folder-outline',  route: 'Carpetas' },
    ],
    empleado: [
        { icon: 'account-outline', route: 'Configuracion' },
        { icon: 'cog-outline',     route: 'Configuracion' },
        { icon: 'bell-outline',    route: null },
        { icon: 'folder-outline',  route: 'Carpetas' },
    ],
};
